### ISSUE TITLE
Survey Details schema does not support non-english forms

### ISSUE THREAD

**Issue by brunowowk** [singer-io/tap-surveymonkey#14]
I'm using this with Stitch and got the following error:

```
Error persisting data to Stitch: 400: {'error': 'Record 1 for table survey_details did not conform to schema:\n#/pages/0/questions/0/answers/choices: 2 schema violations found\n#/pages/0/questions/0/answers/choices/0/description: Nem um pouco provável is not a valid enum value\n#/pages/0/questions/0/answers/choices/10/description: Extremamente provável is not a valid enum value\n'}
```

My surveymonkey for is not in english (it's in pt-br), so the choices do not conform to the schema because the api response is also translated:
https://github.com/singer-io/tap-surveymonkey/blob/master/tap_surveymonkey/schemas/survey_details.json#L316-L320

I guess just removing the enum would solve this

**Comment by ichensvmk** [comment]
https://github.com/singer-io/tap-surveymonkey/pull/16

**Comment by leo-schick** [comment]
https://github.com/singer-io/tap-surveymonkey/pull/16 has been merged so I guess this issue is solved. Can someone from stich close this issue?
