### ISSUE TITLE
Support of more than one survey by integration

### ISSUE THREAD

**Issue by pedro-iatzky** [singer-io/tap-surveymonkey#18]
Currently, if I want to integrate a new survey (using Stitch) I have to create a new integration. This is kind of inconvenient for our use case.

I would like to know if there is some limitation (on the Singer side or on the SurveyMonkey API) that does not allow to replicate all the responses for all the surveys a user has (or at least, to select a list instead of just one) or if this is just a design decision. Furthermore, in the survey_details table all the surveys are being saved, which is kind of inconsistent.

**Comment by leo-schick** [comment]
solved in PR #19

**Comment by rdeshmukh15** [comment]
Released the changes as part of tap-surveymonkey version 2.0.0, to avail this feature you have to create a new surveymonkey integration.
