### ISSUE TITLE
Simplified responses not getting the Heading text

### ISSUE THREAD

**Issue by rj188908** [singer-io/tap-surveymonkey#28]
HI,

We used Stitch V1.0 for several integrations with SurveyMonkey and the data pull and load worked fine. This month we created a new integration and it automatically started using V2. However, it would seem like the call it's making to SM responses API is not including the ?simple=True that is required by SM. We think this is the case as the data pulls don't include the headings for the simplified responses.

Any Prior integration (the ones that used V1 are working normally, pulling the headings).

**Comment by britanybostic** [comment]
Hello! I want to +1 this comment as we are also not receiving the simplified responses and only the response ID associated. Do you have an estimated ETA of when this might be fixed. This was not an issue in V1 as stated above.

**Comment by britanybostic** [comment]
Hello! Wanted to follow up with this. Any help would be much appreciated.

**Comment by pjohn** [comment]
@rdeshmukh15 - We're seeing the same issue as what's been reported above with newer Stitch integrations here. Is this something you're able to look into?

**Comment by rdeshmukh15** [comment]
Created this PR #29 to fix this bug
